language: r

r:
  - release
  - devel

r_check_args: --as-cran --run-donttest

warnings_are_errors: true

cache: packages

r_packages:
  - covr
  - pkgdown

after_success:
  - Rscript -e 'covr::codecov(type="all")'
  - Rscript -e 'pkgdown::build_site()'

notifications:
  slack:
    secure: uc9iy1P9q/ob0Vgyqy7FvH7ofsRPZu05c8en2o3m5l3UmBWNqtVLDTa7MVsQrby4pNeKTsgxR8LTrxbhNftSGbqovzE4LEVZJgH9lwCohFB9LWstSCeZvHsGYPG83yHkIPWIU7v7V2UI21xvAcIZcIubBuu9n28yF1zFVGaj1Ycp3K4lRAOp481Ul4zhiDQX9fmATKX7aW8/iJKHDFeclkykhyYUdGx0ApxGPG6xSBGHqNVVX5K8H4FvTqRvO79e7yY23nUly9pWKhMh8ZAEbTT4Gp055tAgJahE6EoUXTh/D34k/IMv1U8vZsA/RnRg46S0l3IaZv8dSfta9815HH4rmMBAvVRXIabkCO19DF7QMVSUwUo7xfcgqZCAPTKIbl3BtY9jKWd7lgUJFFCDB5wHX99H5WtU8gNS8wUmjM3mzKJ6J4Tn6zdMTKEQTecIg0UdQyMNIL9u0BjgAKdbuzWm0M10MV1ssVlNgh21z+xUB7eRRym0xaqHDSV/fL8z6eVwW435ayKO3VOYwbZJ8F6Qp+F/7XEDtkONjJfuHl5Vou+1b+UKLDVAVPUND+TONXdVrePVCCwpyzygnihz+RAIrJWLP2Wev9qspY1/wUQx890GrOIv5URwHt/chhhzbyM+ryag9vdttsyZ3MCQ22p/atWcBntBWPEtV74OyBw=

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs
  on:
    branch: master
    condition: "$TRAVIS_R_VERSION_STRING = devel"
